site_name: PYTHON LYCÉE
theme:
  name: material
  custom_dir: docs/overrides
  language: fr
  favicon: https://avatars.githubusercontent.com/u/83107633
  logo: https://avatars.githubusercontent.com/u/83107633
  palette:
    primary: white
    accent: light blue
  icon:
    repo: fontawesome/brands/git-alt
  font:
    text: Roboto
  features:
    - navigation.tabs
    - content.tabs.link    
    - toc.integrate

extra:
  version:
    provider: mike
    
repo_url: https://github.com/lfitokyo-ateliernumerique/python-lycee
edit_uri: ""

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences   
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg   
  - admonition
  - pymdownx.details   
  - attr_list
  - md_in_html
  - abbr
 
extra_css:
  - assets/stylesheets/extra.css 
 
extra_javascript:
  - assets/javascripts/extra.js 
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
